/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class jumlah_lain extends javax.swing.JFrame {
    String password = "";
    int tmp;

    /**
     * Creates new form tambah_saldo
     */
    public jumlah_lain(int e) {
        initComponents();
        this.tmp = e;
    }
    
    public void isi(int uang){
        if (tmp - uang < 50000) {
            jOptionPane1.showMessageDialog(null, "Maaf, \nSaldo Anda tidak mencukupi");
        } else {
            tmp -= uang;
            new cek_saldo(tmp).setVisible(true);
            this.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel2 = new javax.swing.JLabel();
        btnEnter1 = new javax.swing.JButton();
        btnClear1 = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();
        jTextFieldPin = new javax.swing.JTextField();
        no1 = new javax.swing.JButton();
        no2 = new javax.swing.JButton();
        no6 = new javax.swing.JButton();
        no10 = new javax.swing.JButton();
        no5 = new javax.swing.JButton();
        no7 = new javax.swing.JButton();
        no4 = new javax.swing.JButton();
        no8 = new javax.swing.JButton();
        noPagar = new javax.swing.JButton();
        no0 = new javax.swing.JButton();
        no9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        noBintang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnEnter1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/5.png"))); // NOI18N
        btnEnter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnter1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnter1);
        btnEnter1.setBounds(240, 380, 90, 40);

        btnClear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/4.png"))); // NOI18N
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear1);
        btnClear1.setBounds(240, 340, 90, 40);

        btnCancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.png"))); // NOI18N
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel1);
        btnCancel1.setBounds(240, 300, 90, 40);

        jTextFieldPin.setEditable(false);
        getContentPane().add(jTextFieldPin);
        jTextFieldPin.setBounds(70, 130, 250, 30);

        no1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no1.setText("1");
        no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no1ActionPerformed(evt);
            }
        });
        getContentPane().add(no1);
        no1.setBounds(70, 300, 50, 40);

        no2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no2.setText("2");
        no2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no2ActionPerformed(evt);
            }
        });
        getContentPane().add(no2);
        no2.setBounds(120, 300, 50, 40);

        no6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no6.setText("6");
        no6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no6ActionPerformed(evt);
            }
        });
        getContentPane().add(no6);
        no6.setBounds(170, 340, 50, 40);

        no10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no10.setText("3");
        no10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no10ActionPerformed(evt);
            }
        });
        getContentPane().add(no10);
        no10.setBounds(170, 300, 50, 40);

        no5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no5.setText("5");
        no5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no5ActionPerformed(evt);
            }
        });
        getContentPane().add(no5);
        no5.setBounds(120, 340, 50, 40);

        no7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no7.setText("7");
        no7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no7ActionPerformed(evt);
            }
        });
        getContentPane().add(no7);
        no7.setBounds(70, 380, 50, 40);

        no4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no4.setText("4");
        no4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no4ActionPerformed(evt);
            }
        });
        getContentPane().add(no4);
        no4.setBounds(70, 340, 50, 40);

        no8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no8.setText("8");
        no8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no8ActionPerformed(evt);
            }
        });
        getContentPane().add(no8);
        no8.setBounds(120, 380, 50, 40);

        noPagar.setText("#");
        getContentPane().add(noPagar);
        noPagar.setBounds(170, 420, 50, 40);

        no0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no0.setText("0");
        no0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no0ActionPerformed(evt);
            }
        });
        getContentPane().add(no0);
        no0.setBounds(120, 420, 50, 40);

        no9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no9.setText("9");
        no9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no9ActionPerformed(evt);
            }
        });
        getContentPane().add(no9);
        no9.setBounds(170, 380, 50, 40);
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 420, 90, 40);

        noBintang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noBintang.setText("*");
        noBintang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBintangActionPerformed(evt);
            }
        });
        getContentPane().add(noBintang);
        noBintang.setBounds(70, 420, 50, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/6.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 410, 550);

        setSize(new java.awt.Dimension(414, 586));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnter1ActionPerformed
        if (password.equals("")) {
            jOptionPane1.showMessageDialog(null, "Masukkan Saldo Dengan Benar!");
        } else {
            int e = Integer.parseInt(password);
            if(e < 50000){
                jOptionPane1.showMessageDialog(null, "Isi Saldo Minimal Rp 50.000!");
            } else {
                isi(e);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnter1ActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        password = "";
        jTextFieldPin.setText(password);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        new menu_transaksi(tmp).setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no1ActionPerformed
        password += "1";
        jTextFieldPin.setText(password);
        // TODO add your handling code here:
    }//GEN-LAST:event_no1ActionPerformed

    private void no2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no2ActionPerformed
        password += "2";
        jTextFieldPin.setText(password);
        // TODO add your handling code here:
    }//GEN-LAST:event_no2ActionPerformed

    private void no10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no10ActionPerformed
        password += "3";
        jTextFieldPin.setText(password);
        // TODO add your handling code here:
    }//GEN-LAST:event_no10ActionPerformed

    private void no6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no6ActionPerformed
        password += "6";
        jTextFieldPin.setText(password);
        // TODO add your handling code here:
    }//GEN-LAST:event_no6ActionPerformed

    private void no5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no5ActionPerformed
        password += "5";
        jTextFieldPin.setText(password);
        // TODO add your handling code here:
    }//GEN-LAST:event_no5ActionPerformed

    private void no4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no4ActionPerformed
        password += "4";
        jTextFieldPin.setText(password);
        // TODO add your handling code here:
    }//GEN-LAST:event_no4ActionPerformed

    private void no7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no7ActionPerformed
        password += "7";
        jTextFieldPin.setText(password);
        // TODO add your handling code here:
    }//GEN-LAST:event_no7ActionPerformed

    private void no8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no8ActionPerformed
        password += "8";
        jTextFieldPin.setText(password);
        // TODO add your handling code here:
    }//GEN-LAST:event_no8ActionPerformed

    private void no9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no9ActionPerformed
        password += "9";
        jTextFieldPin.setText(password);
        // TODO add your handling code here:
    }//GEN-LAST:event_no9ActionPerformed

    private void no0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no0ActionPerformed
        password += "0";
        jTextFieldPin.setText(password);
        // TODO add your handling code here:
    }//GEN-LAST:event_no0ActionPerformed

    private void noBintangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBintangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noBintangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambah_saldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambah_saldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambah_saldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambah_saldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnEnter1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextField jTextFieldPin;
    private javax.swing.JButton no0;
    private javax.swing.JButton no1;
    private javax.swing.JButton no10;
    private javax.swing.JButton no2;
    private javax.swing.JButton no4;
    private javax.swing.JButton no5;
    private javax.swing.JButton no6;
    private javax.swing.JButton no7;
    private javax.swing.JButton no8;
    private javax.swing.JButton no9;
    private javax.swing.JButton noBintang;
    private javax.swing.JButton noPagar;
    // End of variables declaration//GEN-END:variables
}
